import {
    Card,
    Drawer,
    Button,
    Row,
    Switch,
    Upload,
    Col,
    Progress,
    ConfigProvider,
    Layout,
    Statistic,
    Menu,
    Dropdown,
    Breadcrumb,
    List,
    Tag,
    Input,
    Form,
    Checkbox,
    Tabs,
    Pagination,
    Table,
    Spin,
    Modal,
    Select,
    Popover, 
    Avatar,
    Divider,
    Radio,
    DatePicker,
    Descriptions,
    InputNumber
} from 'ant-design-vue';

export default (app) => {
    app.use(InputNumber);
    app.use(DatePicker);
    app.use(Switch);
    app.use(Descriptions);
    app.use(Progress);
    app.use(Radio);
    app.use(Popover);
    app.use(Divider);
    app.use(Modal);
    app.use(Select);
    app.use(Spin);
    app.use(Table);
    app.use(Pagination);
    app.use(Menu);
    app.use(List);
    app.use(Tabs);
    app.use(Dropdown);
    app.use(Button);
    app.use(Avatar);

    app.use(Breadcrumb);
    app.use(ConfigProvider);
    app.use(Tag);
    app.use(Card);
    app.use(Form);
    app.use(Row);
    app.use(Col);
    app.use(Statistic);
    app.use(Input);
    app.use(Layout);
    app.use(Checkbox);
    app.use(Upload);
    app.use(Drawer);
}